name: Deploy

on:
  pull_request:
    types: [closed]
  push:
    tags:
      - 'v*'
      # todo: use semantic versioning for tags after release

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Start Docker Compose
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        run: |
          # Start Docker Compose only for merge requests and tags
          docker-compose -f docker-compose.yaml -p devops_exercise up -d
 