version: '3.3'
services:
  django:
    container_name: postgres
    build: .
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
  db:
    image: postgresql:15
    container_name: postgres
    volumes:
      - "/opt/data/pgsql-devops-exercise:/var/lib/postgresql/data"
    restart: unless-stopped
    expose:
      - 5432
    # todo: uncomment after debug for security
    # ports:
    #   - "127.0.0.1:5432:5432"
